apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    tier: backend
    name: nginx
spec:
  containers:
    - name: nginx
      image: containerregistry075.azurecr.io/nginx:v1
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
